feat: v0.4.1 w/ support for immutable flag on directory
Also checks for read-only filesystems to error out earlier.

diff --git a/run0edit-secureblue.patch b/run0edit-secureblue.patch
--- a/run0edit-secureblue.patch
+++ b/run0edit-secureblue.patch
@@ -4,8 +4,8 @@
  # limitations under the License.
  # ------------------------------------------------------------------------------
  
--readonly version=0.4.0
-+readonly version=0.4.0-secureblue
+-readonly version=0.4.1
++readonly version=0.4.1-secureblue
  
  # Set pipefail if it's supported by the shell, disregard if unsupported.
  # shellcheck disable=SC3040
@@ -22,5 +22,5 @@
 +elif [ -f '/usr/bin/vi' ] && [ -x '/usr/bin/vi' ]; then
 +    editor='/usr/bin/vi'
  else
-     echo "Editor not found. Please install either nano or vi, or write the path to" >&2
-     echo "the text editor of your choice to /etc/run0edit/editor.conf" >&2
+     echo 'Editor not found. Please install either nano or vi, or write the path to' >&2
+     echo 'the text editor of your choice to /etc/run0edit/editor.conf' >&2
