Apache-2.0 license; improved error messages.

diff --git a/run0edit b/run0edit
--- a/run0edit
+++ b/run0edit
@@ -1,30 +1,35 @@
 #!/bin/sh
 # ------------------------------------------------------------------------------
 # run0edit - edit a single file as root.
-# version 0.1.0
+# version 0.1.1
 #
 # Copyright (C) 2025 Daniel Hast
 #
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software
-# Foundation, either version 3 of the License, or (at your option) any later
-# version.
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
 #
-# This program is distributed in the hope that it will be useful, but WITHOUT
-# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
-# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+#     https://www.apache.org/licenses/LICENSE-2.0
 #
-# You should have received a copy of the GNU General Public License along with
-# this program. If not, see <https://www.gnu.org/licenses/>.
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 # ------------------------------------------------------------------------------
 
-if [ "$#" -ne 1 ]; then
-    echo 'run0edit allows a permitted user to edit a file as root.'
-    echo 'Usage: run0edit "path/to/file"'
+if [ "$(id -u)" = 0 ]; then
+    echo 'run0edit should not be run as root.' >&2
     exit 1
 fi
-if [ $(id -u) = 0 ]; then
-    echo 'run0edit should not be run as root.' >&2
+if [ "$#" = 0 ]; then
+    echo 'run0edit allows a permitted user to edit a file as root.'
+    echo 'Usage: run0edit "path/to/file"'
+    exit
+elif [ "$#" -ne 1 ]; then
+    echo 'Error: too many arguments.' >&2
+    echo 'run0edit allows a permitted user to edit a file as root.'
+    echo 'Usage: run0edit "path/to/file"'
     exit 1
 fi
 filename="$1"
